spring:
  application:
    name: http-multiplexing-regular

server:
  port: 8080

provider:
  baseUrl: ${PROVIDER_BASE_URL:http://localhost:9998}

executor:
  corePoolSize: ${CORE_POOL_SIZE:10}
  maxPoolSize: ${MAX_POOL_SIZE:10}
  queueCapacity: ${QUEUE_CAPACITY:10000}